name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dockers/requirements.txt

      - name: Build API service
        run: |
          docker compose -f ./dockers/docker-compose.yml build api

      - name: Start API service
        run: |
          docker compose -f ./dockers/docker-compose.yml up -d api
          
      - name: Run Tests
        run: |
          pytest tests/test_generation.py
