name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: List files for debugging
        run: |
          ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./dockers/requirements.txt

      - name: Build API service
        run: |
          docker compose -f ./dockers/docker-compose.yml build api

      - name: Ensure redis-net network exists
        run: |
          docker network create redis-net || true

      - name: Start API service
        run: |
          docker compose -f ./dockers/docker-compose.yml up -d api
          

      - name: Wait for API service to be ready
        run: |
          until curl -s http://localhost:<API_PORT>/health; do
            echo "Waiting for API service..."
            sleep 5
          done
          
      - name: Run Tests
        run: |
          pytest tests/test_generation.py
